version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: karol_web
    volumes:
      - ./public_html:/usr/share/nginx/html:ro
    ports:
      - "127.0.0.1:8081:80"
    restart: always
